name: bump
channels:
  - conda-forge
  - bioconda
  - defaults
  - xapple
dependencies:
  - build
  - autopaths
  - plumbing
  - sh
  - rich
  - twine
  - pdoc
  - rattler-build
  - pyrattler-recipe-autogen
  - anaconda-client
  - conda-token