name: bump
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - build
  - autopaths
  - plumbing
  - sh
  - rich
  - twine
  - pdoc
  - grayskull
  - anaconda-client
  - rattler-build
  - pyrattler-recipe-autogen
